echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "We are learning AWS, Azure DevOps and DevSecOps"
echo "I am learning in batch-29"
echo "new line added and removing older lines"
echo "I am learing the Devops"
echo "I am learing the Java"